# Generated by Django 3.2 on 2023-03-22 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='City',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid Number', regex='^[0-9+]{5}-[0-9+]{7}-[0-9]{1}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='Contact_Number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid Number', regex='^((\\+92)?(0092)?(92)?(0)?)(3)([0-9]{9})$')]),
        ),
    ]
