# Generated by Django 3.2 on 2023-03-23 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230322_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Mechanic_Email', models.EmailField(default='abc@abc.com', max_length=254)),
                ('Full_Name', models.CharField(max_length=100)),
                ('CNIC_Number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid Number', regex='^[0-9+]{5}-[0-9+]{7}-[0-9]{1}$')])),
                ('City', models.CharField(max_length=50)),
                ('Contact_Number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid Number', regex='^((\\+92)?(0092)?(92)?(0)?)(3)([0-9]{9})$')])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='User_Email',
            field=models.EmailField(default='abc@abc.com', max_length=254),
        ),
    ]
