# Generated by Django 3.2 on 2023-03-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230323_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mechanic',
            new_name='MechanicRegistration',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserRegistration',
        ),
    ]
