# Generated by Django 4.1.2 on 2023-05-04 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mechanicregistration_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Card_Number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid Format', regex='^4[0-9]{12}(?:[0-9]{3})?$')])),
                ('cvv', models.CharField(max_length=3)),
                ('Expiry_date', models.DateField()),
            ],
        ),
    ]
