# Generated by Django 4.2.1 on 2023-05-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cardetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicregistration',
            name='Experience',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
