# Generated by Django 3.2 on 2023-03-22 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Full_Name', models.CharField(max_length=100)),
                ('CNIC_Number', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('Contact_Number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid number', regex='^((\\+92)?(0092)?(92)?(0)?)(3)([0-9]{9})$/gm')])),
            ],
        ),
    ]
