# Generated by Django 3.2 on 2023-03-22 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230322_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CNIC_Number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid Number', regex='^[0-9+]{5}-[0-9+]{7}-[0-9]{1}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='City',
            field=models.CharField(max_length=50),
        ),
    ]
