# Generated by Django 4.1.2 on 2023-04-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230323_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicregistration',
            name='Services',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
