# Generated by Django 4.1.7 on 2023-05-14 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('services', models.CharField(max_length=550, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mechanicregistration',
            name='CNIC_Number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid CNIC Number', regex='^[0-9+]{5}-[0-9+]{7}-[0-9]{1}$')]),
        ),
        migrations.AlterField(
            model_name='mechanicregistration',
            name='Contact_Number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^((\\+92)?(0092)?(92)?(0)?)(3)([0-9]{9})$')]),
        ),
        migrations.AlterField(
            model_name='mechanicregistration',
            name='Services',
            field=models.CharField(max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='CNIC_Number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid CNIC Number', regex='^[0-9+]{5}-[0-9+]{7}-[0-9]{1}$')]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='Contact_Number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^((\\+92)?(0092)?(92)?(0)?)(3)([0-9]{9})$')]),
        ),
    ]
