# Generated by Django 4.2.1 on 2023-05-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_detail_alter_mechanicregistration_cnic_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='location',
            new_name='Workshop_Location',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='name',
            new_name='Workshop_Name',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='phone',
            new_name='Workshop_Phone',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='services',
            new_name='Workshop_Services',
        ),
    ]
