# Generated by Django 4.2.1 on 2023-05-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_location_detail_workshop_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Company', models.CharField(max_length=50)),
                ('Car_Model', models.CharField(max_length=50)),
                ('Engine_Type', models.CharField(max_length=20)),
                ('Engine_Capacity', models.CharField(max_length=550)),
                ('Mileage', models.CharField(max_length=550)),
            ],
        ),
    ]
